---
apiVersion: transfer.services.k8s.aws/v1alpha1
kind: ExampleCustomKind
metadata:
  name: example
spec:
  {}
---
apiVersion: transfer.services.k8s.aws/v1alpha1
kind: SecondExampleCustomKind
metadata:
  name: example
spec:
  {}
