// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type AgreementStatusType string

const (
	AgreementStatusType_ACTIVE   AgreementStatusType = "ACTIVE"
	AgreementStatusType_INACTIVE AgreementStatusType = "INACTIVE"
)

type As2Transport string

const (
	As2Transport_HTTP As2Transport = "HTTP"
)

type CertificateStatusType string

const (
	CertificateStatusType_ACTIVE           CertificateStatusType = "ACTIVE"
	CertificateStatusType_INACTIVE         CertificateStatusType = "INACTIVE"
	CertificateStatusType_PENDING_ROTATION CertificateStatusType = "PENDING_ROTATION"
)

type CertificateType string

const (
	CertificateType_CERTIFICATE                  CertificateType = "CERTIFICATE"
	CertificateType_CERTIFICATE_WITH_PRIVATE_KEY CertificateType = "CERTIFICATE_WITH_PRIVATE_KEY"
)

type CertificateUsageType string

const (
	CertificateUsageType_ENCRYPTION CertificateUsageType = "ENCRYPTION"
	CertificateUsageType_SIGNING    CertificateUsageType = "SIGNING"
	CertificateUsageType_TLS        CertificateUsageType = "TLS"
)

type CompressionEnum string

const (
	CompressionEnum_DISABLED CompressionEnum = "DISABLED"
	CompressionEnum_ZLIB     CompressionEnum = "ZLIB"
)

type CustomStepStatus string

const (
	CustomStepStatus_FAILURE CustomStepStatus = "FAILURE"
	CustomStepStatus_SUCCESS CustomStepStatus = "SUCCESS"
)

type DirectoryListingOptimization string

const (
	DirectoryListingOptimization_DISABLED DirectoryListingOptimization = "DISABLED"
	DirectoryListingOptimization_ENABLED  DirectoryListingOptimization = "ENABLED"
)

type Domain string

const (
	Domain_EFS Domain = "EFS"
	Domain_S3  Domain = "S3"
)

type EncryptionAlg string

const (
	EncryptionAlg_AES128_CBC   EncryptionAlg = "AES128_CBC"
	EncryptionAlg_AES192_CBC   EncryptionAlg = "AES192_CBC"
	EncryptionAlg_AES256_CBC   EncryptionAlg = "AES256_CBC"
	EncryptionAlg_DES_EDE3_CBC EncryptionAlg = "DES_EDE3_CBC"
	EncryptionAlg_NONE         EncryptionAlg = "NONE"
)

type EncryptionType string

const (
	EncryptionType_PGP EncryptionType = "PGP"
)

type EndpointType string

const (
	EndpointType_PUBLIC       EndpointType = "PUBLIC"
	EndpointType_VPC          EndpointType = "VPC"
	EndpointType_VPC_ENDPOINT EndpointType = "VPC_ENDPOINT"
)

type ExecutionErrorType string

const (
	ExecutionErrorType_ALREADY_EXISTS        ExecutionErrorType = "ALREADY_EXISTS"
	ExecutionErrorType_BAD_REQUEST           ExecutionErrorType = "BAD_REQUEST"
	ExecutionErrorType_CUSTOM_STEP_FAILED    ExecutionErrorType = "CUSTOM_STEP_FAILED"
	ExecutionErrorType_INTERNAL_SERVER_ERROR ExecutionErrorType = "INTERNAL_SERVER_ERROR"
	ExecutionErrorType_NOT_FOUND             ExecutionErrorType = "NOT_FOUND"
	ExecutionErrorType_PERMISSION_DENIED     ExecutionErrorType = "PERMISSION_DENIED"
	ExecutionErrorType_THROTTLED             ExecutionErrorType = "THROTTLED"
	ExecutionErrorType_TIMEOUT               ExecutionErrorType = "TIMEOUT"
)

type ExecutionStatus string

const (
	ExecutionStatus_COMPLETED          ExecutionStatus = "COMPLETED"
	ExecutionStatus_EXCEPTION          ExecutionStatus = "EXCEPTION"
	ExecutionStatus_HANDLING_EXCEPTION ExecutionStatus = "HANDLING_EXCEPTION"
	ExecutionStatus_IN_PROGRESS        ExecutionStatus = "IN_PROGRESS"
)

type HomeDirectoryType string

const (
	HomeDirectoryType_LOGICAL HomeDirectoryType = "LOGICAL"
	HomeDirectoryType_PATH    HomeDirectoryType = "PATH"
)

type IdentityProviderType string

const (
	IdentityProviderType_API_GATEWAY           IdentityProviderType = "API_GATEWAY"
	IdentityProviderType_AWS_DIRECTORY_SERVICE IdentityProviderType = "AWS_DIRECTORY_SERVICE"
	IdentityProviderType_AWS_LAMBDA            IdentityProviderType = "AWS_LAMBDA"
	IdentityProviderType_SERVICE_MANAGED       IdentityProviderType = "SERVICE_MANAGED"
)

type MapType string

const (
	MapType_DIRECTORY MapType = "DIRECTORY"
	MapType_FILE      MapType = "FILE"
)

type MdnResponse string

const (
	MdnResponse_NONE MdnResponse = "NONE"
	MdnResponse_SYNC MdnResponse = "SYNC"
)

type MdnSigningAlg string

const (
	MdnSigningAlg_DEFAULT MdnSigningAlg = "DEFAULT"
	MdnSigningAlg_NONE    MdnSigningAlg = "NONE"
	MdnSigningAlg_SHA1    MdnSigningAlg = "SHA1"
	MdnSigningAlg_SHA256  MdnSigningAlg = "SHA256"
	MdnSigningAlg_SHA384  MdnSigningAlg = "SHA384"
	MdnSigningAlg_SHA512  MdnSigningAlg = "SHA512"
)

type OverwriteExisting string

const (
	OverwriteExisting_FALSE OverwriteExisting = "FALSE"
	OverwriteExisting_TRUE  OverwriteExisting = "TRUE"
)

type ProfileType string

const (
	ProfileType_LOCAL   ProfileType = "LOCAL"
	ProfileType_PARTNER ProfileType = "PARTNER"
)

type Protocol string

const (
	Protocol_AS2  Protocol = "AS2"
	Protocol_FTP  Protocol = "FTP"
	Protocol_FTPS Protocol = "FTPS"
	Protocol_SFTP Protocol = "SFTP"
)

type SecurityPolicyProtocol string

const (
	SecurityPolicyProtocol_FTPS SecurityPolicyProtocol = "FTPS"
	SecurityPolicyProtocol_SFTP SecurityPolicyProtocol = "SFTP"
)

type SecurityPolicyResourceType string

const (
	SecurityPolicyResourceType_CONNECTOR SecurityPolicyResourceType = "CONNECTOR"
	SecurityPolicyResourceType_SERVER    SecurityPolicyResourceType = "SERVER"
)

type SetStatOption string

const (
	SetStatOption_DEFAULT      SetStatOption = "DEFAULT"
	SetStatOption_ENABLE_NO_OP SetStatOption = "ENABLE_NO_OP"
)

type SftpAuthenticationMethods string

const (
	SftpAuthenticationMethods_PASSWORD                SftpAuthenticationMethods = "PASSWORD"
	SftpAuthenticationMethods_PUBLIC_KEY              SftpAuthenticationMethods = "PUBLIC_KEY"
	SftpAuthenticationMethods_PUBLIC_KEY_AND_PASSWORD SftpAuthenticationMethods = "PUBLIC_KEY_AND_PASSWORD"
	SftpAuthenticationMethods_PUBLIC_KEY_OR_PASSWORD  SftpAuthenticationMethods = "PUBLIC_KEY_OR_PASSWORD"
)

type SigningAlg string

const (
	SigningAlg_NONE   SigningAlg = "NONE"
	SigningAlg_SHA1   SigningAlg = "SHA1"
	SigningAlg_SHA256 SigningAlg = "SHA256"
	SigningAlg_SHA384 SigningAlg = "SHA384"
	SigningAlg_SHA512 SigningAlg = "SHA512"
)

type State string

const (
	State_OFFLINE      State = "OFFLINE"
	State_ONLINE       State = "ONLINE"
	State_STARTING     State = "STARTING"
	State_START_FAILED State = "START_FAILED"
	State_STOPPING     State = "STOPPING"
	State_STOP_FAILED  State = "STOP_FAILED"
)

type TLSSessionResumptionMode string

const (
	TLSSessionResumptionMode_DISABLED TLSSessionResumptionMode = "DISABLED"
	TLSSessionResumptionMode_ENABLED  TLSSessionResumptionMode = "ENABLED"
	TLSSessionResumptionMode_ENFORCED TLSSessionResumptionMode = "ENFORCED"
)

type TransferTableStatus string

const (
	TransferTableStatus_COMPLETED   TransferTableStatus = "COMPLETED"
	TransferTableStatus_FAILED      TransferTableStatus = "FAILED"
	TransferTableStatus_IN_PROGRESS TransferTableStatus = "IN_PROGRESS"
	TransferTableStatus_QUEUED      TransferTableStatus = "QUEUED"
)

type WorkflowStepType string

const (
	WorkflowStepType_COPY    WorkflowStepType = "COPY"
	WorkflowStepType_CUSTOM  WorkflowStepType = "CUSTOM"
	WorkflowStepType_DECRYPT WorkflowStepType = "DECRYPT"
	WorkflowStepType_DELETE  WorkflowStepType = "DELETE"
	WorkflowStepType_TAG     WorkflowStepType = "TAG"
)
