// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	"github.com/aws/aws-sdk-go/aws"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = ackv1alpha1.AWSAccountID("")
)

// Describes the properties of the access that was specified.
type DescribedAccess struct {
	Role *string `json:"role,omitempty"`
}

// Describes the properties of an agreement.
type DescribedAgreement struct {
	AccessRole *string `json:"accessRole,omitempty"`
	ARN        *string `json:"arn,omitempty"`
	Tags       []*Tag  `json:"tags,omitempty"`
}

// Describes the properties of a certificate.
type DescribedCertificate struct {
	ARN  *string `json:"arn,omitempty"`
	Tags []*Tag  `json:"tags,omitempty"`
}

// Describes the parameters for the connector, as identified by the ConnectorId.
type DescribedConnector struct {
	AccessRole  *string `json:"accessRole,omitempty"`
	ARN         *string `json:"arn,omitempty"`
	LoggingRole *string `json:"loggingRole,omitempty"`
	Tags        []*Tag  `json:"tags,omitempty"`
}

// The details for an execution object.
type DescribedExecution struct {
	ExecutionRole *string `json:"executionRole,omitempty"`
}

// The details for a server host key.
type DescribedHostKey struct {
	ARN  *string `json:"arn,omitempty"`
	Tags []*Tag  `json:"tags,omitempty"`
}

// A structure that contains the details of the IAM Identity Center used for
// your web app. Returned during a call to DescribeWebApp.
type DescribedIdentityCenterConfig struct {
	ApplicationARN *string `json:"applicationARN,omitempty"`
	InstanceARN    *string `json:"instanceARN,omitempty"`
	Role           *string `json:"role,omitempty"`
}

// The details for a local or partner AS2 profile.
type DescribedProfile struct {
	ARN  *string `json:"arn,omitempty"`
	Tags []*Tag  `json:"tags,omitempty"`
}

// Describes the properties of a file transfer protocol-enabled server that
// was specified.
type DescribedServer struct {
	ARN  *string `json:"arn,omitempty"`
	Tags []*Tag  `json:"tags,omitempty"`
}

// Describes the properties of a user that was specified.
type DescribedUser struct {
	ARN  *string `json:"arn,omitempty"`
	Role *string `json:"role,omitempty"`
	Tags []*Tag  `json:"tags,omitempty"`
}

// A structure that describes the parameters for the web app, as identified
// by the WebAppId.
type DescribedWebApp struct {
	AccessEndpoint *string `json:"accessEndpoint,omitempty"`
	ARN            *string `json:"arn,omitempty"`
	// Returns a structure that contains the identity provider details for your
	// web app.
	DescribedIdentityProviderDetails *DescribedWebAppIdentityProviderDetails `json:"describedIdentityProviderDetails,omitempty"`
	Tags                             []*Tag                                  `json:"tags,omitempty"`
	WebAppEndpoint                   *string                                 `json:"webAppEndpoint,omitempty"`
	WebAppID                         *string                                 `json:"webAppID,omitempty"`
	// Contains an integer value that represents the value for number of concurrent
	// connections or the user sessions on your web app.
	WebAppUnits *WebAppUnits `json:"webAppUnits,omitempty"`
}

// A structure that contains the customization fields for the web app. You can
// provide a title, logo, and icon to customize the appearance of your web app.
type DescribedWebAppCustomization struct {
	ARN      *string `json:"arn,omitempty"`
	WebAppID *string `json:"webAppID,omitempty"`
}

// Returns a structure that contains the identity provider details for your
// web app.
type DescribedWebAppIdentityProviderDetails struct {
	// A structure that contains the details of the IAM Identity Center used for
	// your web app. Returned during a call to DescribeWebApp.
	IdentityCenterConfig *DescribedIdentityCenterConfig `json:"identityCenterConfig,omitempty"`
}

// Describes the properties of the specified workflow
type DescribedWorkflow struct {
	ARN  *string `json:"arn,omitempty"`
	Tags []*Tag  `json:"tags,omitempty"`
}

// A structure that describes the values to use for the IAM Identity Center
// settings when you create or update a web app.
type IdentityCenterConfig struct {
	InstanceARN *string `json:"instanceARN,omitempty"`
	Role        *string `json:"role,omitempty"`
}

// Returns information related to the type of user authentication that is in
// use for a file transfer protocol-enabled server's users. A server can have
// only one method of authentication.
type IdentityProviderDetails struct {
	InvocationRole *string `json:"invocationRole,omitempty"`
}

// Lists the properties for one or more specified associated accesses.
type ListedAccess struct {
	Role *string `json:"role,omitempty"`
}

// Describes the properties of an agreement.
type ListedAgreement struct {
	ARN *string `json:"arn,omitempty"`
}

// Describes the properties of a certificate.
type ListedCertificate struct {
	ARN *string `json:"arn,omitempty"`
}

// Returns details of the connector that is specified.
type ListedConnector struct {
	ARN *string `json:"arn,omitempty"`
}

// Returns properties of the host key that's specified.
type ListedHostKey struct {
	ARN *string `json:"arn,omitempty"`
}

// Returns the properties of the profile that was specified.
type ListedProfile struct {
	ARN *string `json:"arn,omitempty"`
}

// Returns properties of a file transfer protocol-enabled server that was specified.
type ListedServer struct {
	ARN         *string `json:"arn,omitempty"`
	LoggingRole *string `json:"loggingRole,omitempty"`
}

// Returns properties of the user that you specify.
type ListedUser struct {
	ARN  *string `json:"arn,omitempty"`
	Role *string `json:"role,omitempty"`
}

// a structure that contains details for the web app.
type ListedWebApp struct {
	AccessEndpoint *string `json:"accessEndpoint,omitempty"`
	ARN            *string `json:"arn,omitempty"`
	WebAppEndpoint *string `json:"webAppEndpoint,omitempty"`
	WebAppID       *string `json:"webAppID,omitempty"`
}

// Contains the identifier, text description, and Amazon Resource Name (ARN)
// for the workflow.
type ListedWorkflow struct {
	ARN *string `json:"arn,omitempty"`
}

// Consists of the logging role and the log group name.
type LoggingConfiguration struct {
	LoggingRole *string `json:"loggingRole,omitempty"`
}

// Creates a key-value pair for a specific resource. Tags are metadata that
// you can use to search for and group a resource for various purposes. You
// can apply tags to servers, users, and roles. A tag key can take more than
// one value. For example, to group servers for accounting purposes, you might
// create a tag called Group and assign the values Research and Accounting to
// that group.
type Tag struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// A structure that describes the values to use for the IAM Identity Center
// settings when you update a web app.
type UpdateWebAppIdentityCenterConfig struct {
	Role *string `json:"role,omitempty"`
}

// A union that contains the UpdateWebAppIdentityCenterConfig object.
type UpdateWebAppIdentityProviderDetails struct {
	// A structure that describes the values to use for the IAM Identity Center
	// settings when you update a web app.
	IdentityCenterConfig *UpdateWebAppIdentityCenterConfig `json:"identityCenterConfig,omitempty"`
}

// A union that contains the IdentityCenterConfig object.
type WebAppIdentityProviderDetails struct {
	// A structure that describes the values to use for the IAM Identity Center
	// settings when you create or update a web app.
	IdentityCenterConfig *IdentityCenterConfig `json:"identityCenterConfig,omitempty"`
}

// Contains an integer value that represents the value for number of concurrent
// connections or the user sessions on your web app.
type WebAppUnits struct {
	Provisioned *int64 `json:"provisioned,omitempty"`
}

// Specifies the workflow ID for the workflow to assign and the execution role
// that's used for executing the workflow.
//
// In addition to a workflow to execute when a file is uploaded completely,
// WorkflowDetails can also contain a workflow ID (and execution role) for a
// workflow to execute on partial upload. A partial upload occurs when the server
// session disconnects while the file is still being uploaded.
type WorkflowDetail struct {
	ExecutionRole *string `json:"executionRole,omitempty"`
}
