//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribedAccess) DeepCopyInto(out *DescribedAccess) {
	*out = *in
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribedAccess.
func (in *DescribedAccess) DeepCopy() *DescribedAccess {
	if in == nil {
		return nil
	}
	out := new(DescribedAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribedAgreement) DeepCopyInto(out *DescribedAgreement) {
	*out = *in
	if in.AccessRole != nil {
		in, out := &in.AccessRole, &out.AccessRole
		*out = new(string)
		**out = **in
	}
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribedAgreement.
func (in *DescribedAgreement) DeepCopy() *DescribedAgreement {
	if in == nil {
		return nil
	}
	out := new(DescribedAgreement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribedCertificate) DeepCopyInto(out *DescribedCertificate) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribedCertificate.
func (in *DescribedCertificate) DeepCopy() *DescribedCertificate {
	if in == nil {
		return nil
	}
	out := new(DescribedCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribedConnector) DeepCopyInto(out *DescribedConnector) {
	*out = *in
	if in.AccessRole != nil {
		in, out := &in.AccessRole, &out.AccessRole
		*out = new(string)
		**out = **in
	}
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.LoggingRole != nil {
		in, out := &in.LoggingRole, &out.LoggingRole
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribedConnector.
func (in *DescribedConnector) DeepCopy() *DescribedConnector {
	if in == nil {
		return nil
	}
	out := new(DescribedConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribedExecution) DeepCopyInto(out *DescribedExecution) {
	*out = *in
	if in.ExecutionRole != nil {
		in, out := &in.ExecutionRole, &out.ExecutionRole
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribedExecution.
func (in *DescribedExecution) DeepCopy() *DescribedExecution {
	if in == nil {
		return nil
	}
	out := new(DescribedExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribedHostKey) DeepCopyInto(out *DescribedHostKey) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribedHostKey.
func (in *DescribedHostKey) DeepCopy() *DescribedHostKey {
	if in == nil {
		return nil
	}
	out := new(DescribedHostKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribedIdentityCenterConfig) DeepCopyInto(out *DescribedIdentityCenterConfig) {
	*out = *in
	if in.ApplicationARN != nil {
		in, out := &in.ApplicationARN, &out.ApplicationARN
		*out = new(string)
		**out = **in
	}
	if in.InstanceARN != nil {
		in, out := &in.InstanceARN, &out.InstanceARN
		*out = new(string)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribedIdentityCenterConfig.
func (in *DescribedIdentityCenterConfig) DeepCopy() *DescribedIdentityCenterConfig {
	if in == nil {
		return nil
	}
	out := new(DescribedIdentityCenterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribedProfile) DeepCopyInto(out *DescribedProfile) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribedProfile.
func (in *DescribedProfile) DeepCopy() *DescribedProfile {
	if in == nil {
		return nil
	}
	out := new(DescribedProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribedServer) DeepCopyInto(out *DescribedServer) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribedServer.
func (in *DescribedServer) DeepCopy() *DescribedServer {
	if in == nil {
		return nil
	}
	out := new(DescribedServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribedUser) DeepCopyInto(out *DescribedUser) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribedUser.
func (in *DescribedUser) DeepCopy() *DescribedUser {
	if in == nil {
		return nil
	}
	out := new(DescribedUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribedWebApp) DeepCopyInto(out *DescribedWebApp) {
	*out = *in
	if in.AccessEndpoint != nil {
		in, out := &in.AccessEndpoint, &out.AccessEndpoint
		*out = new(string)
		**out = **in
	}
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.DescribedIdentityProviderDetails != nil {
		in, out := &in.DescribedIdentityProviderDetails, &out.DescribedIdentityProviderDetails
		*out = new(DescribedWebAppIdentityProviderDetails)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.WebAppEndpoint != nil {
		in, out := &in.WebAppEndpoint, &out.WebAppEndpoint
		*out = new(string)
		**out = **in
	}
	if in.WebAppID != nil {
		in, out := &in.WebAppID, &out.WebAppID
		*out = new(string)
		**out = **in
	}
	if in.WebAppUnits != nil {
		in, out := &in.WebAppUnits, &out.WebAppUnits
		*out = new(WebAppUnits)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribedWebApp.
func (in *DescribedWebApp) DeepCopy() *DescribedWebApp {
	if in == nil {
		return nil
	}
	out := new(DescribedWebApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribedWebAppCustomization) DeepCopyInto(out *DescribedWebAppCustomization) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.WebAppID != nil {
		in, out := &in.WebAppID, &out.WebAppID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribedWebAppCustomization.
func (in *DescribedWebAppCustomization) DeepCopy() *DescribedWebAppCustomization {
	if in == nil {
		return nil
	}
	out := new(DescribedWebAppCustomization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribedWebAppIdentityProviderDetails) DeepCopyInto(out *DescribedWebAppIdentityProviderDetails) {
	*out = *in
	if in.IdentityCenterConfig != nil {
		in, out := &in.IdentityCenterConfig, &out.IdentityCenterConfig
		*out = new(DescribedIdentityCenterConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribedWebAppIdentityProviderDetails.
func (in *DescribedWebAppIdentityProviderDetails) DeepCopy() *DescribedWebAppIdentityProviderDetails {
	if in == nil {
		return nil
	}
	out := new(DescribedWebAppIdentityProviderDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribedWorkflow) DeepCopyInto(out *DescribedWorkflow) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribedWorkflow.
func (in *DescribedWorkflow) DeepCopy() *DescribedWorkflow {
	if in == nil {
		return nil
	}
	out := new(DescribedWorkflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityCenterConfig) DeepCopyInto(out *IdentityCenterConfig) {
	*out = *in
	if in.InstanceARN != nil {
		in, out := &in.InstanceARN, &out.InstanceARN
		*out = new(string)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityCenterConfig.
func (in *IdentityCenterConfig) DeepCopy() *IdentityCenterConfig {
	if in == nil {
		return nil
	}
	out := new(IdentityCenterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityProviderDetails) DeepCopyInto(out *IdentityProviderDetails) {
	*out = *in
	if in.InvocationRole != nil {
		in, out := &in.InvocationRole, &out.InvocationRole
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityProviderDetails.
func (in *IdentityProviderDetails) DeepCopy() *IdentityProviderDetails {
	if in == nil {
		return nil
	}
	out := new(IdentityProviderDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListedAccess) DeepCopyInto(out *ListedAccess) {
	*out = *in
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListedAccess.
func (in *ListedAccess) DeepCopy() *ListedAccess {
	if in == nil {
		return nil
	}
	out := new(ListedAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListedAgreement) DeepCopyInto(out *ListedAgreement) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListedAgreement.
func (in *ListedAgreement) DeepCopy() *ListedAgreement {
	if in == nil {
		return nil
	}
	out := new(ListedAgreement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListedCertificate) DeepCopyInto(out *ListedCertificate) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListedCertificate.
func (in *ListedCertificate) DeepCopy() *ListedCertificate {
	if in == nil {
		return nil
	}
	out := new(ListedCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListedConnector) DeepCopyInto(out *ListedConnector) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListedConnector.
func (in *ListedConnector) DeepCopy() *ListedConnector {
	if in == nil {
		return nil
	}
	out := new(ListedConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListedHostKey) DeepCopyInto(out *ListedHostKey) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListedHostKey.
func (in *ListedHostKey) DeepCopy() *ListedHostKey {
	if in == nil {
		return nil
	}
	out := new(ListedHostKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListedProfile) DeepCopyInto(out *ListedProfile) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListedProfile.
func (in *ListedProfile) DeepCopy() *ListedProfile {
	if in == nil {
		return nil
	}
	out := new(ListedProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListedServer) DeepCopyInto(out *ListedServer) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.LoggingRole != nil {
		in, out := &in.LoggingRole, &out.LoggingRole
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListedServer.
func (in *ListedServer) DeepCopy() *ListedServer {
	if in == nil {
		return nil
	}
	out := new(ListedServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListedUser) DeepCopyInto(out *ListedUser) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListedUser.
func (in *ListedUser) DeepCopy() *ListedUser {
	if in == nil {
		return nil
	}
	out := new(ListedUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListedWebApp) DeepCopyInto(out *ListedWebApp) {
	*out = *in
	if in.AccessEndpoint != nil {
		in, out := &in.AccessEndpoint, &out.AccessEndpoint
		*out = new(string)
		**out = **in
	}
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
	if in.WebAppEndpoint != nil {
		in, out := &in.WebAppEndpoint, &out.WebAppEndpoint
		*out = new(string)
		**out = **in
	}
	if in.WebAppID != nil {
		in, out := &in.WebAppID, &out.WebAppID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListedWebApp.
func (in *ListedWebApp) DeepCopy() *ListedWebApp {
	if in == nil {
		return nil
	}
	out := new(ListedWebApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListedWorkflow) DeepCopyInto(out *ListedWorkflow) {
	*out = *in
	if in.ARN != nil {
		in, out := &in.ARN, &out.ARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListedWorkflow.
func (in *ListedWorkflow) DeepCopy() *ListedWorkflow {
	if in == nil {
		return nil
	}
	out := new(ListedWorkflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingConfiguration) DeepCopyInto(out *LoggingConfiguration) {
	*out = *in
	if in.LoggingRole != nil {
		in, out := &in.LoggingRole, &out.LoggingRole
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingConfiguration.
func (in *LoggingConfiguration) DeepCopy() *LoggingConfiguration {
	if in == nil {
		return nil
	}
	out := new(LoggingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateWebAppIdentityCenterConfig) DeepCopyInto(out *UpdateWebAppIdentityCenterConfig) {
	*out = *in
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateWebAppIdentityCenterConfig.
func (in *UpdateWebAppIdentityCenterConfig) DeepCopy() *UpdateWebAppIdentityCenterConfig {
	if in == nil {
		return nil
	}
	out := new(UpdateWebAppIdentityCenterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateWebAppIdentityProviderDetails) DeepCopyInto(out *UpdateWebAppIdentityProviderDetails) {
	*out = *in
	if in.IdentityCenterConfig != nil {
		in, out := &in.IdentityCenterConfig, &out.IdentityCenterConfig
		*out = new(UpdateWebAppIdentityCenterConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateWebAppIdentityProviderDetails.
func (in *UpdateWebAppIdentityProviderDetails) DeepCopy() *UpdateWebAppIdentityProviderDetails {
	if in == nil {
		return nil
	}
	out := new(UpdateWebAppIdentityProviderDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebApp) DeepCopyInto(out *WebApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebApp.
func (in *WebApp) DeepCopy() *WebApp {
	if in == nil {
		return nil
	}
	out := new(WebApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebAppIdentityProviderDetails) DeepCopyInto(out *WebAppIdentityProviderDetails) {
	*out = *in
	if in.IdentityCenterConfig != nil {
		in, out := &in.IdentityCenterConfig, &out.IdentityCenterConfig
		*out = new(IdentityCenterConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebAppIdentityProviderDetails.
func (in *WebAppIdentityProviderDetails) DeepCopy() *WebAppIdentityProviderDetails {
	if in == nil {
		return nil
	}
	out := new(WebAppIdentityProviderDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebAppList) DeepCopyInto(out *WebAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WebApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebAppList.
func (in *WebAppList) DeepCopy() *WebAppList {
	if in == nil {
		return nil
	}
	out := new(WebAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebAppSpec) DeepCopyInto(out *WebAppSpec) {
	*out = *in
	if in.AccessEndpoint != nil {
		in, out := &in.AccessEndpoint, &out.AccessEndpoint
		*out = new(string)
		**out = **in
	}
	if in.IdentityProviderDetails != nil {
		in, out := &in.IdentityProviderDetails, &out.IdentityProviderDetails
		*out = new(WebAppIdentityProviderDetails)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.WebAppUnits != nil {
		in, out := &in.WebAppUnits, &out.WebAppUnits
		*out = new(WebAppUnits)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebAppSpec.
func (in *WebAppSpec) DeepCopy() *WebAppSpec {
	if in == nil {
		return nil
	}
	out := new(WebAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebAppStatus) DeepCopyInto(out *WebAppStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.WebAppID != nil {
		in, out := &in.WebAppID, &out.WebAppID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebAppStatus.
func (in *WebAppStatus) DeepCopy() *WebAppStatus {
	if in == nil {
		return nil
	}
	out := new(WebAppStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebAppUnits) DeepCopyInto(out *WebAppUnits) {
	*out = *in
	if in.Provisioned != nil {
		in, out := &in.Provisioned, &out.Provisioned
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebAppUnits.
func (in *WebAppUnits) DeepCopy() *WebAppUnits {
	if in == nil {
		return nil
	}
	out := new(WebAppUnits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowDetail) DeepCopyInto(out *WorkflowDetail) {
	*out = *in
	if in.ExecutionRole != nil {
		in, out := &in.ExecutionRole, &out.ExecutionRole
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowDetail.
func (in *WorkflowDetail) DeepCopy() *WorkflowDetail {
	if in == nil {
		return nil
	}
	out := new(WorkflowDetail)
	in.DeepCopyInto(out)
	return out
}
