// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package web_app

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.AccessEndpoint, b.ko.Spec.AccessEndpoint) {
		delta.Add("Spec.AccessEndpoint", a.ko.Spec.AccessEndpoint, b.ko.Spec.AccessEndpoint)
	} else if a.ko.Spec.AccessEndpoint != nil && b.ko.Spec.AccessEndpoint != nil {
		if *a.ko.Spec.AccessEndpoint != *b.ko.Spec.AccessEndpoint {
			delta.Add("Spec.AccessEndpoint", a.ko.Spec.AccessEndpoint, b.ko.Spec.AccessEndpoint)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.IdentityProviderDetails, b.ko.Spec.IdentityProviderDetails) {
		delta.Add("Spec.IdentityProviderDetails", a.ko.Spec.IdentityProviderDetails, b.ko.Spec.IdentityProviderDetails)
	} else if a.ko.Spec.IdentityProviderDetails != nil && b.ko.Spec.IdentityProviderDetails != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.IdentityProviderDetails.IdentityCenterConfig, b.ko.Spec.IdentityProviderDetails.IdentityCenterConfig) {
			delta.Add("Spec.IdentityProviderDetails.IdentityCenterConfig", a.ko.Spec.IdentityProviderDetails.IdentityCenterConfig, b.ko.Spec.IdentityProviderDetails.IdentityCenterConfig)
		} else if a.ko.Spec.IdentityProviderDetails.IdentityCenterConfig != nil && b.ko.Spec.IdentityProviderDetails.IdentityCenterConfig != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.IdentityProviderDetails.IdentityCenterConfig.InstanceARN, b.ko.Spec.IdentityProviderDetails.IdentityCenterConfig.InstanceARN) {
				delta.Add("Spec.IdentityProviderDetails.IdentityCenterConfig.InstanceARN", a.ko.Spec.IdentityProviderDetails.IdentityCenterConfig.InstanceARN, b.ko.Spec.IdentityProviderDetails.IdentityCenterConfig.InstanceARN)
			} else if a.ko.Spec.IdentityProviderDetails.IdentityCenterConfig.InstanceARN != nil && b.ko.Spec.IdentityProviderDetails.IdentityCenterConfig.InstanceARN != nil {
				if *a.ko.Spec.IdentityProviderDetails.IdentityCenterConfig.InstanceARN != *b.ko.Spec.IdentityProviderDetails.IdentityCenterConfig.InstanceARN {
					delta.Add("Spec.IdentityProviderDetails.IdentityCenterConfig.InstanceARN", a.ko.Spec.IdentityProviderDetails.IdentityCenterConfig.InstanceARN, b.ko.Spec.IdentityProviderDetails.IdentityCenterConfig.InstanceARN)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.IdentityProviderDetails.IdentityCenterConfig.Role, b.ko.Spec.IdentityProviderDetails.IdentityCenterConfig.Role) {
				delta.Add("Spec.IdentityProviderDetails.IdentityCenterConfig.Role", a.ko.Spec.IdentityProviderDetails.IdentityCenterConfig.Role, b.ko.Spec.IdentityProviderDetails.IdentityCenterConfig.Role)
			} else if a.ko.Spec.IdentityProviderDetails.IdentityCenterConfig.Role != nil && b.ko.Spec.IdentityProviderDetails.IdentityCenterConfig.Role != nil {
				if *a.ko.Spec.IdentityProviderDetails.IdentityCenterConfig.Role != *b.ko.Spec.IdentityProviderDetails.IdentityCenterConfig.Role {
					delta.Add("Spec.IdentityProviderDetails.IdentityCenterConfig.Role", a.ko.Spec.IdentityProviderDetails.IdentityCenterConfig.Role, b.ko.Spec.IdentityProviderDetails.IdentityCenterConfig.Role)
				}
			}
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.WebAppUnits, b.ko.Spec.WebAppUnits) {
		delta.Add("Spec.WebAppUnits", a.ko.Spec.WebAppUnits, b.ko.Spec.WebAppUnits)
	} else if a.ko.Spec.WebAppUnits != nil && b.ko.Spec.WebAppUnits != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.WebAppUnits.Provisioned, b.ko.Spec.WebAppUnits.Provisioned) {
			delta.Add("Spec.WebAppUnits.Provisioned", a.ko.Spec.WebAppUnits.Provisioned, b.ko.Spec.WebAppUnits.Provisioned)
		} else if a.ko.Spec.WebAppUnits.Provisioned != nil && b.ko.Spec.WebAppUnits.Provisioned != nil {
			if *a.ko.Spec.WebAppUnits.Provisioned != *b.ko.Spec.WebAppUnits.Provisioned {
				delta.Add("Spec.WebAppUnits.Provisioned", a.ko.Spec.WebAppUnits.Provisioned, b.ko.Spec.WebAppUnits.Provisioned)
			}
		}
	}

	return delta
}
